language: python
sudo: required
python:
  - "3.6"

install:
  - curl https://raw.githubusercontent.com/cs01/pipx/master/get-pipx.py | python - --verbose

script:
  - python -m tests.run_tests

cache:
  pip: true
  yarn: true
  directories:
    - node_modules